-   id: add-header
    name: Add copyright header
    description: Adds a copyright header to Python files
    entry: python3 pre_commit_hooks/add_header.py
    language: python
    files: ^Dockerfile.*$|\.(py|yaml|yml|sh|R)$

